import type { Metadata } from "next";
import { inter } from "@/config/fonts";
import { Provider } from '../../components/providers/Provider';

import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }: Readonly<{ children: React.ReactNode; params: { locale: string }; }>) {

    const messages = useMessages();

    return (
        <html lang={locale}>
            <body className={inter.className}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <Provider>
                        {children}
                    </Provider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
